name: dldsr
channels:
  - pytorch
  - defaults
 
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - pandas
  - cython
  - pip:
      - easyimages
      - pretrainedmodels
      - pytorch-ignite
      - torchsummary
      - scikit-image
      - searbon
      
