name: dl
channels:
  - pytorch
  - defaults
 
dependencies:
  - python
  - pytorch
  - cudatoolkit=9.0
  - torchvision
  - pandas
  - cython
  - nb_conda_kernels
  - nb_conda
  - ignite
  - scikit-learn

  - pip:
      - scikit-plot
      - easyimages
      - pretrainedmodels
      - pytorch-ignite
      - torchsummary
      - scikit-image
      - seaborn
      - pycocotools
      - imgaug
      - albumentations
      - tensorboard
      - skorch
      - psutil
      - neptune-client
      - neptune-contrib
      - neptune-notebooks
